image: ghcr.io/home-assistant/{arch}-base-debian
build_from: "mattjeanes/teslamateagile:v1.16.0"
cosign:
  identity: https://github.com/home-assistant/docker-base/.*
args:
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.6.2
labels:
  io.hass.base.name: debian
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base